
// -----SIGNUP and LOGIN------------------------------------


// Signup
POST http://localhost:8080/signUp
Content-Type: application/json

{
  "email": "1@1.com",
  "password": "1"
}

###

// Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "1@1.com",
  "password": "1"
}

###

// ---Authentication-----------------------------------------

GET http://localhost:8080/api/auth/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAMS5jb20iLCJpYXQiOjE2ODUxMTMyMDAsImV4cCI6MTY4NTExNjgwMH0.D5Lc5p3gjvVcRgfUtrRWV5P5kRxt7BsdQalKdqQw0XM
Content-Type: application/json

###


// -----USERS-------------------------------------------------


// GetAll
GET http://localhost:8080/users
Content-Type: application/json
###

// Get
GET http://localhost:8080/users/d@d.com

###


// GetUser
GET http://localhost:8080/auth/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAMS5jb20iLCJpYXQiOjE2ODUyMDM0NDEsImV4cCI6MTY4NTIwNzA0MX0.0vGGsyWFvbjmaPllE2tRFE7RTup7xpUy5dzibBCRbxw
###

// Create
POST http://localhost:8080/createUser
Content-Type: application/json

{
  "email": "1@1.com",
  "password": "1"
}

###

// PUT
PUT http://localhost:8080/users/1@1.com
Content-Type: application/json

{
  "email": "1@1.com",
  "password": "1"
}
###

// PATCH Admin
PATCH http://localhost:8080/users/1@1.com/admin
Content-Type: application/json


###

// DELETE
DELETE http://localhost:8080/users/1@2.com
###



// ------EVENTS--------------------------------------------

// GetAll
GET http://localhost:8080/events
Content-Type: application/json
###

// Get by ID
GET http://localhost:8080/events/64661ed1098eb5382b98d4e7
Content-Type: application/json
###

// Create
POST http://localhost:8080/createEvent
Content-Type: application/json

{
  "name": "New Event",
  "date": "2023-05-19",
  "time": "10:00 AM",
  "location": "Copenhagen",
  "description": "Event description",
  "image": "event-image.jpg",
  "ticket_max": 100,
  "ticket_left": 100,
  "price": 10.99
}

###

// Update
PUT http://localhost:8080/events/646626129b266f2520e3a38c
Content-Type: application/json

{
  "name": "Updated Event Name",
  "date": "2023-05-19",
  "time": "11:00 AM",
  "description": "Updated event description",
  "image": "updated-event-image.jpg",
  "ticket_max": 150,
  "ticket_left": 120,
  "price": 15.99
}

###

// Update tickets

PUT http://localhost:8080/events/647e69c10013c3441e166073/updateTickets
Content-Type: application/json

{
  "ticket_left": 110
}


###

// Delete
DELETE http://localhost:8080/events/64661ed1098eb5382b98d4e7
###


 // ---Orders-----------------------------------

 GET http://localhost:8080/orders
Content-Type: application/json

###

GET http://localhost:8080/orders/email/1@1.com
Content-Type: application/json

###

POST http://localhost:8080/orders
Content-Type: application/json

{
  "eventId": "647098722d766860c7f44b76",
  "paymentMethodId": "pm_123456789",
  "tickets": 4,
  "amount": 1000,
  "email": "example@example.com"
}


###

PUT http://localhost:8080/order/646626129b266f2520e3a38c
Content-Type: application/json

{
  "amount": 15.99
}

###

DELETE http://localhost:8080/order/64661ed1098eb5382b98d4e7
Content-Type: application/json

###